{% set name = "bigframes" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bigframes-{{ version }}.tar.gz
  sha256: 814a7009d461caa0221adca4d86e3ef0bf80339cb19c0c1b0d8763f4c7c2fc84

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - cloudpickle >=2.0.0
    - fsspec >=2023.3.0
    - gcsfs >=2023.3.0
    - geopandas >=0.12.2
    - google-auth >=2.15.0,<3.0dev
    - google-cloud-bigquery-core >=3.16.0
# ModuleNotFoundError: No module named 'google.cloud.bigquery_storage_v1'
    - google-cloud-bigquery-storage >=2.0.0
    - google-cloud-functions >=1.12.0
    - google-cloud-bigquery-connection >=1.12.0
    - google-cloud-iam >=2.12.1
    - google-cloud-resource-manager >=1.10.3
    - google-cloud-storage >=2.0.0
    - ibis-framework >=8.0.0,<9.0.0dev
#ibis-framework 7.2.0 has requirement pins[gcs]<1,>=0.8.3, but you have pins 0.0.0.
    - ibis-framework-core >=8.0.0,<9.0.0
    - pins >=0.8.3,<1
#bigframes 0.18.0 has requirement ibis-framework[bigquery]<7.2.0dev,>=7.1.0, but you have ibis-framework 7.2.0.
    - ibis-bigquery >=8.0.0,<9.0.0
    - jellyfish >=0.8.9
    - pandas >=1.5.0
#ibis-framework 8.0.0 has requirement pyarrow<16,>=2, but you have pyarrow 16.0.0
    - pyarrow >=8.0.0
    - pydata-google-auth >=1.8.2
    - requests >=2.27.1
    - scikit-learn >=1.2.2
    - sqlalchemy >=1.4,<3.0dev
    - sqlglot >=20.8.0,<=20.11
    - tabulate >=0.9
    - ipywidgets >=7.7.1
    - humanize >=4.6.0
    - matplotlib-base >=3.7.1


test:
  imports:
    - bigframes
    - bigframes_vendored
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-dataframes
  summary: BigQuery DataFrames -- scalable analytics and machine learning with BigQuery
  license: BSD-4-Clause AND Apache-2.0 AND BSD-3-Clause
  license_file:
    - LICENSE
    - third_party/bigframes_vendored/ibis/LICENSE.txt
    - third_party/bigframes_vendored/cpython/LICENSE
    - third_party/bigframes_vendored/pandas/LICENSE
    - third_party/bigframes_vendored/google_cloud_bigquery/LICENSE
    - third_party/bigframes_vendored/xgboost/LICENSE
    - third_party/bigframes_vendored/sklearn/COPYING

extra:
  recipe-maintainers:
    - rxm7706
